version: '3.7'
services: 
  postgres:
    container_name: postgres_container
    image: postgres:14.2-alpine
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: api_container
    depends_on:
      - postgres
    ports:
      - "3080:3080"